version: '3'
services:
  sr-gen4:
    container_name: sr-gen4
    build: ./
    restart: on-failure
    ports:
      - 8084:8084
    logging:
      driver: "fluentd"
      options:
        fluentd-address: tcp://host.docker.internal:24224
    networks:
      - sr-gen4

networks:
  sr-gen4:
    driver: bridge
    attachable: true