version: '3'
services:
  sr-gen3:
    container_name: sr-gen3
    build: ./
    restart: on-failure
    ports:
      - 8083:8083
    logging:
      driver: "fluentd"
      options:
        fluentd-address: tcp://host.docker.internal:24224
    networks:
      - sr-gen3

networks:
  sr-gen3:
    driver: bridge
    attachable: true